name: demo2

channels:
  - defaults
dependencies:
  - pip
  - numpy
  - pandas=0.24.2
  - python==3.7
  - scikit-learn==0.20.3
  - jupyter=1.0.0=py37_7
  - pip:
    - mlflow==0.9.1 #https://mlflow-snapshots.s3-us-west-2.amazonaws.com/mlflow-1.0.0.rc0-1173.fb8a711-py2.py3-none-any.whl
    - seaborn
    - jupyter
    - azureml-sdk
    - pylint