name: mlflowenv

channels:
  - defaults
dependencies:
  - pip
  - numpy
  - pandas=0.24.2
  - python==3.7
  - scikit-learn==0.20.3
  - jupyter=1.0.0=py37_7
  - pip:
    - mlflow
    - seaborn
    - jupyter
    - azureml-sdk
    - pylint