name: mlflowenv

channels:
  - defaults
dependencies:
  - pip
  - numpy
  - pandas
  - python==3.6.8
  - scikit-learn
  - jupyter=1.0.0
  - pip:
    - mlflow
    - seaborn
    - azureml-sdk
    - pylint